### PR TITLE
Add headers when loading url

### PR DESCRIPTION
**Pull request by readytopark**
iOS/Android tested. It would also be good if we support headers in `reloadUrl`

### CODE REVIEW

**Comment by readytopark** [comment]
Fixes #61

**Comment by Code-PLeX** [comment]
working on android only for now [#141](https://github.com/dart-flitter/flutter_webview_plugin/pull/141)

**Comment by Code-PLeX** [comment]
when will you add this commit to release?

**Comment by lejard-h** [comment]
soon :)

**Pull request merged**
