### PR TITLE
Flutter 2.0.

### PR DESCRIPTION
**Pull request by ramah**
Suggestion for Migrating to Flutter 2.0 and Dart with Null safety.
Tests seems to fail.
Will need help

### CODE REVIEW

**Review by andzejsw — APPROVED** [review]

**Comment by guillaume-fortin-keyneosoft** [comment]
I think you need to change github action files

flutter-version: '1.7.8+hotfix.4' must change with current version of flutter: 2.0.4

**Comment by ramah** [comment]
Hello @guillaume-fortin-keyneosoft  Thx for your suggestion. We Will see.

**Comment by guillaume-fortin-keyneosoft** [comment]
@ramah, I will help you tomorrow for fix unit test with mockito in null safety mode.

**Comment by guillaume-fortin-keyneosoft** [comment]
@ramah, sorry, i didn't take the time to answer you.

You can change the MockMethodChannel in this projet by this implementation:

```
class MockMethodChannel extends Mock implements MethodChannel {
  @override
  Future<T?> invokeMethod<T>(String method, [ dynamic arguments ]) async {
    return Future<T?>.value(super.noSuchMethod(Invocation.method(#invokeMethod, [arguments])));
  }
}
```

You can test with this command:  flutter test

**Comment by ramah** [comment]
No Problem. I even tried to find you.
I'll will tried it and will tell you.

**Comment by ramah** [comment]
@guillaume-fortin-keyneosoft  Merci. C'est OK.
Comme c'est ma première contribution il faut une validation.

**Comment by charafau** [comment]
merged and released as 0.4.0 https://github.com/fluttercommunity/flutter_webview_plugin/pull/893

**Pull request closed without merging**
