### PR TITLE
Null safety support

### LINKED ISSUE #880: Null safety support
Null safety is stable now in flutter. Any plan to migrate flutter_webview_plugin to null safety?

### PR DESCRIPTION
**Pull request by themisir**
Fixes #880

### CODE REVIEW

**Comment by andzejsw** [comment]
@charafau please take a look, when you have time.

**Comment by charafau** [comment]
@andzejsw  I'm sorry but I'm no longer maintainer of this package, I'd also suggest to use official webview plugin if possible

**Comment by andzejsw** [comment]
@charafau do you know who is maintainer? Currently this plugin contains feature, which isn't in official plugin. For official plugin i have made PR, which isn't implemented for quite long time. Till then I need this plugin in my project.

**Comment by TheMisir** [comment]
> @andzejsw I'm sorry but I'm no longer maintainer of this package, I'd also suggest to use official webview plugin if possible

Official plugin doesn't works great with device keyboard and have some scrolling issue. Both issues are critical for me because, I need WebViews to collect credit card details, which requires seamless keyboard interaction.

**Review by ortal83cohen — APPROVED** [review]

**Comment by charafau** [comment]
I passed message to flutter community regarding this issue

**Comment by AlexV525** [comment]
> Official plugin doesn't works great with device keyboard and have some scrolling issue. Both issues are critical for me because, I need WebViews to collect credit card details, which requires seamless keyboard interaction.

By enable the hybrid composition, keyboard issues and scroll performance regression should be no longer exist. Did you enabled it?

**Comment by TheMisir** [comment]
> > Official plugin doesn't works great with device keyboard and have some scrolling issue. Both issues are critical for me because, I need WebViews to collect credit card details, which requires seamless keyboard interaction.
> 
> By enable the hybrid composition, keyboard issues and scroll performance regression should be no longer exist. Did you enabled it?

Have not tried because this one does already works.

**Comment by augustorsouza** [comment]
Let's merge this guys?

**Comment by charafau** [comment]
merged and released as 0.4.0

**Pull request merged**
