### PR TITLE
Scrollbar functionality to Web view

### PR DESCRIPTION
**Pull request by lakexyde**
Thank you for your effort on this plugin.

I added the ability to remove scrollbars in Webview. The default is true, so developers can always change it to false. I also included it in the README.md

Thanks.

### CODE REVIEW

**Comment by gedw99** [comment]
Can i ask what the use case is out of curiosity ?

**Comment by lakexyde** [comment]
The user launches a new Webview scaffold. Adding the ```scrollBar``` parameter as ```false```. 
It sets the vertical scrollbar visibility to false on android and ios. So that user can scroll vertically without the scrollbar on the right.
For example: 
```
Navigator.of(context).push(
  new MaterialPageRoute(
    builder: (_){
      return new WebviewScaffold(
        url: post.url,
        scrollBar: false,
        appBar: new AppBar(
          title: new Text("Just a title"),
        )
      );
    }
  )
);
```

**Comment by gedw99** [comment]
Thank you

**Comment by lejard-h** [comment]
Looks great thanks

**Comment by lakexyde** [comment]
Thanks.

**Pull request merged**
