### PR TITLE
Support file upload via WebView on Android

### PR DESCRIPTION
**Pull request by peter9teufel**
The Android WebView does not support file uploads via input type file out of the box. To support file uploads on various android versions the WebviewManager has been extended with the needed file chooser options and the AcitivityResultListener Plugin is used to pass the results of the onActivityResult call to the WebviewManager.

### CODE REVIEW

**Comment by lejard-h** [comment]
Thanks,

do you know if it is builtin with iOS ?

**Comment by peter9teufel** [comment]
it worked out of the box on iOS in my tests.

What may should be mentioned in the read me, is that file upload on Android requires the read storage permission to work properly

**Comment by peter9teufel** [comment]
I am currently working on a further improvement on this as I figured out that if you switch between WebviewPlugin and native UI in the app the activity result listener that is needed for file upload callbacks can make problems.
I am now working on an improvement to allow un/registering the AcitivityResultListener

**Comment by peter9teufel** [comment]
It was just a Nullpointer caused by interference with other tasks using onActivityResult - it should be fixed now (Y)

**Pull request merged**
